import { Maven_Pro, Roboto, Bebas_Neue } from "next/font/google";
import Nabvar from "@/components/Navbar";
import "./globals.css";

const inter = Maven_Pro({
  subsets: ['latin'],
})

const roboto = Roboto({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
})

const bebas = Bebas_Neue({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-bebas',
})


export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto.variable} ${bebas.variable}`}>
        <Nabvar />
        {children}
      </body>
    </html>
  );
}
