import { Maven_Pro, Roboto, Lexend } from "next/font/google";
import Nabvar from "@/components/Navbar";
import "./globals.css";

const inter = Maven_Pro({
  subsets: ['latin'],
})

const roboto = Roboto({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
})

const lexend = Lexend({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lexend',
})


export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto.variable} ${lexend.variable}`}>
        <Nabvar />
        {children}
      </body>
    </html>
  );
}
